name: Actualizar Leaderboard LoL

on:
  schedule:
    - cron: '*/2 * * * *' # Intenta ejecutar cada 2 minutos
  workflow_dispatch: # Esto nos deja un botón para ejecutarlo manual si queremos

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Descargar el repositorio
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar librerías
      run: pip install -r requirements.txt

    - name: Ejecutar el script de Python y conectar con Riot
      env:
        RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
      run: python main.py

    - name: Guardar los nuevos LP y subirlos a la web
      run: |
        git config --global user.name 'Bot de la Grieta'
        git config --global user.email 'action@github.com'
        git add datos.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Actualizando rankeds automágicamente" && git push)